# Copyright 2026 hobisatelit
# https://github.com/hobisatelit/ssdv2sat
# License: GPL-3.0-or-later
[app]
#ssdv = ssdv.exe
#sox = sox.exe
ssdv = /usr/bin/ssdv
sox = /usr/bin/sox
sox_device_win = CABLE Output


