#ADEVICE 0 0
CHANNEL 0
ARATE 48000

MYCALL N0CALL
#LAPAN A2/IO86, use 1200 or 2400
MODEM 1200
#MODEM 2400

# Silversat, use 9600
#MODEM 9600 

# disable fix_bits, so all packet will be passed to rx.py script, enabling recovering broken ssdv packet with fec / reed solomon enabled
FIX_BITS NONE AX25 PASSALL

#FIX_BITS 1 AX25 PASSALL

#disable il2ptx if you send ssdv with fec / reed solomon
#default: IL2PTX disabled
#IL2PTX

#PTT VOX
#TIMEOUT 1000
#TRANSMIT 1 

KISSPORT 8001



