#ADEVICE plughw:1,0
CHANNEL 0
ARATE 48000

MYCALL N0CALL
# LAPAN A2/IO86, use 1200 or 2400
MODEM 1200
#MODEM 2400

# Silversat, use 9600
#MODEM 9600

#PTT VOX
#TIMEOUT 1000
#TRANSMIT 1    

# recommendation:
# fix_bits none ax25 passall
# so all packet will be passed to rx.py script, enabling recovering broken ssdv packet with fec / reed solomon enabled
FIX_BITS NONE AX25 PASSALL
#FIX_BITS 1 AX25 PASSALL

# recommendation:
# disable il2ptx if you send ssdv with fec / reed solomon
# default: IL2PTX disabled
#IL2PTX

KISSPORT 8001

